# **CS 559-WS1: Machine Learning: Fundamentals and Applications**
# **Homework 2**

**Name: Ankit Dhandharia**

**CWID: 20033031**

In [24]:
# Import required libraries
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression

# **Question 1: Naive Bayes Classification**

## **Load dataset**

In [13]:
X, y = datasets.make_blobs(n_samples=400, n_features=5, centers=4, cluster_std=2, random_state=100)

## **Part a: Compute prior probability of each class**

In [14]:
unique_classes, class_counts = np.unique(y, return_counts=True)
p_Ck = class_counts / len(y)
print("Prior probabilities p(Ck):")
for k, prob in enumerate(p_Ck):
    print(f"Class {k}: {prob}")

Prior probabilities p(Ck):
Class 0: 0.25
Class 1: 0.25
Class 2: 0.25
Class 3: 0.25


## **Part b: Compute likelihood p(X|Ck)**

In [15]:
means = []
vars = []
for k in range(4):
    class_data = X[y == k]
    means.append(np.mean(class_data, axis=0))
    vars.append(np.var(class_data, axis=0))

p_X_given_Ck = np.zeros((len(X), 4))
for k in range(4):
    p_X_given_Ck[:, k] = np.prod(
        1/np.sqrt(2*np.pi*vars[k]) *
        np.exp(-0.5*((X - means[k])**2)/vars[k]),
        axis=1
    )

print("First few likelihood values p(X|Ck):")
print(p_X_given_Ck[:5])

First few likelihood values p(X|Ck):
[[4.35737431e-19 5.83470609e-36 1.65617426e-23 6.68636482e-05]
 [3.37890351e-18 3.74816408e-29 3.43372487e-07 1.15217600e-30]
 [1.51666045e-04 1.60401115e-28 6.93442926e-23 4.77305265e-19]
 [6.77565445e-16 4.96289533e-36 6.07868727e-18 1.26523237e-04]
 [2.41064492e-24 9.40159239e-50 1.02819772e-25 4.75405911e-06]]


## **Part c: Compute posterior probability p(Ck|X)**